[package]
name = "bds_enhancer"
version = "0.3.2"
edition = "2024"
rust-version = "1.88"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
lazy_static = "1.4.0"
json = "0.12.4"
sourcemap = "9.3.2"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
strip = true
